# Generated by Django 5.0.3 on 2025-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_artisan_artisanrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artisans/profile_images/'),
        ),
    ]
