# Generated by Django 5.0.3 on 2025-04-15 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_artisan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='artisan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.artisan'),
        ),
    ]
